import { Head, Link } from '@inertiajs/react';
import { useState } from 'react';

import Modal from '../../../Components/Modal';
import AuthenticatedLayout from '../../../Layouts/AuthenticatedLayout';

function NutritionMetric({ title, value, goal, percent, description }) {
    return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-sm font-bold">{title}</h2><span className="text-xs font-semibold text-slate-500">{Math.round(percent)}%</span></div><p className="mt-4 text-3xl font-extrabold">{value} <span className="text-sm text-slate-400">/ {goal}</span></p><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-cyan-500" style={{ width: `${Math.min(percent, 100)}%` }} /></div><p className="mt-3 text-xs leading-5 text-slate-500">{description}</p></section>;
}

export default function Index({ metrics, foods, recommendations, urls }) {
    const [slide, setSlide] = useState(0);
    const [recommendationIndex, setRecommendationIndex] = useState(0);
    const [open, setOpen] = useState(false);
    const visibleFoods = [0, 1, 2].map((offset) => foods[(slide + offset) % foods.length]);
    return <AuthenticatedLayout><Head title="Alimentación inteligente" />
        <header className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-extrabold">Alimentación con IA</h1><p className="mt-2 text-slate-500">Recomendaciones basadas en tus métricas registradas.</p></div><Link href={urls.create} className="rounded-2xl bg-cyan-600 px-5 py-3 font-semibold text-white">Registrar comida</Link></header>
        <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid gap-5 md:grid-cols-3">{visibleFoods.map((food) => <article key={food.name} className="overflow-hidden rounded-3xl bg-slate-900 text-white shadow-sm"><img src={food.image} alt={food.name} className="h-48 w-full object-cover" /><div className="p-4"><h2 className="font-bold">{food.name}</h2><p className="text-sm text-slate-300">{food.calories}</p></div></article>)}</div><div className="mt-5 flex items-center justify-center gap-3"><button type="button" aria-label="Anterior" onClick={() => setSlide((value) => (value - 1 + foods.length) % foods.length)} className="rounded-full border px-4 py-2">Anterior</button><span className="text-sm text-slate-500">{slide + 1} de {foods.length}</span><button type="button" aria-label="Siguiente" onClick={() => setSlide((value) => (value + 1) % foods.length)} className="rounded-full border px-4 py-2">Siguiente</button></div><div className="mt-6 text-center"><button type="button" onClick={() => setOpen(true)} className="rounded-2xl bg-cyan-600 px-6 py-3 font-bold text-white">Generar recomendación IA</button></div></section>
        <div className="mt-6 grid gap-5 md:grid-cols-3"><NutritionMetric title="Calorías" value={metrics.caloriesToday} goal={`${metrics.calorieGoal} kcal`} percent={metrics.caloriePercent} description="Consumo estimado según los carbohidratos registrados." /><NutritionMetric title="Carbohidratos" value={`${metrics.carbsToday} g`} goal={`${metrics.carbGoal} g`} percent={metrics.carbPercent} description="Los carbohidratos son la fuente principal de energía y picos de glucosa." /><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Tip nutricional</h2><p className="mt-4 text-sm leading-6 text-slate-600">{metrics.dailyTip}</p><div className="mt-4 flex gap-2"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">Fibra</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">Proteína</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">Bajo IG</span></div></section></div>
        <Modal open={open} title="Analizador DiabTrack IA" onClose={() => setOpen(false)} actions={<><button type="button" onClick={() => setOpen(false)} className="rounded-xl px-4 py-2 font-semibold">Cerrar</button><button type="button" onClick={() => setRecommendationIndex((value) => (value + 1) % recommendations.length)} className="rounded-xl bg-cyan-600 px-4 py-2 font-semibold text-white">Siguiente idea</button></>}><div className="rounded-2xl border-l-4 border-cyan-500 bg-cyan-50 p-4"><h3 className="font-bold text-cyan-800">Estado actual</h3><p className="mt-2 text-sm">Has consumido <strong>{metrics.carbsToday} g</strong> de carbohidratos. Tu glucosa se mantiene en <strong>{metrics.latestGlucose ?? '--'} mg/dL</strong>.</p><h3 className="mt-4 font-bold text-emerald-700">Recomendación IA</h3><p className="mt-2 text-sm">{recommendations[recommendationIndex]}</p></div><p className="mt-3 text-xs text-slate-500">Esta recomendación es generada algorítmicamente.</p></Modal>
    </AuthenticatedLayout>;
}
