import { Head, Link, useForm } from '@inertiajs/react';
import ChartColumn from 'lucide-react/dist/esm/icons/chart-column.mjs';
import ChartLine from 'lucide-react/dist/esm/icons/chart-line.mjs';
import Bot from 'lucide-react/dist/esm/icons/bot.mjs';
import ClipboardPlus from 'lucide-react/dist/esm/icons/clipboard-plus.mjs';
import CircleCheck from 'lucide-react/dist/esm/icons/circle-check.mjs';
import Clock3 from 'lucide-react/dist/esm/icons/clock-3.mjs';
import DropletOff from 'lucide-react/dist/esm/icons/droplet-off.mjs';
import Lightbulb from 'lucide-react/dist/esm/icons/lightbulb.mjs';
import LinkIcon from 'lucide-react/dist/esm/icons/link.mjs';
import NotepadText from 'lucide-react/dist/esm/icons/notepad-text.mjs';
import Plus from 'lucide-react/dist/esm/icons/plus.mjs';
import ShieldHeart from 'lucide-react/dist/esm/icons/shield-check.mjs';
import SlidersHorizontal from 'lucide-react/dist/esm/icons/sliders-horizontal.mjs';
import TriangleAlert from 'lucide-react/dist/esm/icons/triangle-alert.mjs';
import Weight from 'lucide-react/dist/esm/icons/weight.mjs';

import ChartCard from '../Components/ChartCard';
import FormInput from '../Components/FormInput';
import FormSelect from '../Components/FormSelect';
import SubmitButton from '../Components/SubmitButton';
import Table from '../Components/Table';
import AuthenticatedLayout from '../Layouts/AuthenticatedLayout';

function ProgressMetric({ title, value, unit, current, goal, percent }) {
    return <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{title}</p><p className="mt-2 text-3xl font-extrabold">{value ?? '--'}{unit}</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-cyan-500" style={{ width: `${Math.min(percent, 100)}%` }} /></div><p className="mt-2 text-xs text-slate-500">Hoy: {current} · Meta: {goal}</p></section>;
}

const glucoseStatusStyles = {
    normal: { icon: CircleCheck, classes: 'border-emerald-200 bg-emerald-50 text-emerald-700' },
    elevada: { icon: TriangleAlert, classes: 'border-red-200 bg-red-50 text-red-700' },
    baja: { icon: DropletOff, classes: 'border-amber-200 bg-amber-50 text-amber-700' },
};

function GlucoseStatusBadge({ statusKey, label }) {
    if (!label) return null;
    const config = glucoseStatusStyles[statusKey] ?? { icon: CircleCheck, classes: 'border-slate-200 bg-slate-50 text-slate-600' };
    const Icon = config.icon;
    return <span className={`inline-flex items-center gap-1.5 rounded-full border px-3 py-2 text-xs font-semibold ${config.classes}`}><Icon size={14} />{label}</span>;
}

export default function Dashboard({ metrics, recentLogs, tip, profile, urls, inviteCode }) {
    const weightForm = useForm({ weight: '' });
    const inviteForm = useForm({ role: 'caregiver' });
    return <AuthenticatedLayout><Head title="Dashboard" />
        <div className="grid gap-6 xl:grid-cols-[minmax(0,3fr)_minmax(19rem,1fr)]">
            <aside className="order-2 space-y-6 xl:order-2">
                <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h1 className="text-lg font-bold text-cyan-700">Gestión DiabTrack</h1><nav className="mt-4 grid gap-2"><div className="flex items-center gap-3 rounded-2xl bg-slate-50 p-3 opacity-55"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-orange-300 text-white"><Bot size={21} /></span><span><strong className="block">Nutrición IA</strong><small className="text-xs text-slate-500">Planificación de comidas</small><span className="mt-1 block w-fit rounded-full border border-orange-200 bg-orange-50 px-2 py-0.5 text-[10px] text-orange-500">Próximamente</span></span></div><Link href={urls.summary} className="flex items-center gap-3 rounded-2xl bg-slate-50 p-3 font-semibold"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-cyan-500 text-white"><ChartColumn size={21} /></span><span><strong className="block">Gráficos</strong><small className="text-xs font-normal text-slate-500">Análisis de tendencias</small></span></Link><Link href={urls.vitals} className="flex items-center gap-3 rounded-2xl bg-slate-50 p-3 font-semibold"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-500 text-white"><ClipboardPlus size={21} /></span><span><strong className="block">Registrar</strong><small className="text-xs font-normal text-slate-500">Añadir entrada diaria</small></span></Link><Link href={urls.profile} className="flex items-center gap-3 rounded-2xl bg-slate-50 p-3 font-semibold"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-500 text-white"><SlidersHorizontal size={21} /></span><span><strong className="block">Ajustes</strong><small className="text-xs font-normal text-slate-500">Configurar perfil</small></span></Link></nav></section>
                <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-slate-500"><Lightbulb size={16} className="text-cyan-500" />Tip del día</h2>{tip.isAi && <span className="rounded-full bg-cyan-50 px-2 py-1 text-xs font-semibold text-cyan-700">IA</span>}</div><p className="mt-4 text-sm leading-6 text-slate-600">{tip.text}</p></section>
                <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xs font-bold uppercase tracking-wide text-slate-500">Síntomas hoy</h2><div className="mt-4 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-full bg-emerald-50 text-emerald-600"><ShieldHeart size={20} /></span><div><p className="text-3xl font-extrabold">{metrics.symptomsToday}</p><p className="text-sm text-slate-500">{metrics.symptomsToday === 1 ? 'síntoma reportado' : 'síntomas reportados'}</p></div></div></section>
                <section className="hidden rounded-3xl border border-slate-200 bg-white p-6 shadow-sm xl:block"><h2 className="text-xs font-bold uppercase tracking-wide text-slate-500">Actividad reciente</h2><div className="mt-4 flex items-center gap-3"><Clock3 size={20} className="text-emerald-500" /><div><strong className="block text-sm">Última medición</strong><span className="text-xs text-slate-500">{recentLogs[0]?.date ?? 'Sin registros'}</span></div></div></section>
                <form onSubmit={(event) => { event.preventDefault(); inviteForm.post(urls.invite, { preserveScroll: true }); }} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-sm font-bold"><LinkIcon size={17} className="text-cyan-600" />Código de vinculación</h2><FormSelect id="invite_role" label="Compartir con" value={inviteForm.data.role} onChange={(event) => inviteForm.setData('role', event.target.value)}><option value="caregiver">Cuidador</option><option value="doctor">Médico</option></FormSelect><SubmitButton className="mt-3" processing={inviteForm.processing}>Generar código</SubmitButton>{inviteCode && <p className="mt-4 rounded-xl bg-cyan-50 p-3 text-center font-mono text-xl font-bold tracking-widest text-cyan-800">{inviteCode}</p>}</form>
            </aside>
            <section className="order-1 space-y-6 xl:order-1">
                <div className="flex items-center justify-between"><h1 className="text-2xl font-bold text-slate-900">Resumen de Datos <span className="text-cyan-500">Total</span></h1><span className="hidden rounded-full border border-slate-200 bg-white px-4 py-1 text-sm text-slate-500 sm:block">{new Intl.DateTimeFormat('es-MX', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date())}</span></div>
                {metrics.needsWeightUpdate && <form onSubmit={(event) => { event.preventDefault(); weightForm.post(urls.weight, { preserveScroll: true, onSuccess: () => weightForm.reset() }); }} className="flex flex-col gap-6 rounded-3xl border border-slate-200 border-l-[5px] border-l-cyan-500 bg-white p-6 shadow-sm lg:flex-row lg:items-center"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-cyan-50 text-cyan-600"><Weight size={20} /></span><div className="min-w-0 flex-1"><strong className="block text-slate-900">Actualización Mensual de Peso</strong><p className="text-xs text-slate-500">{metrics.lastWeight ? `Último registro: ${metrics.lastWeight} kg — Hace más de 30 días` : 'Aún no has registrado tu peso este mes'}</p></div><div className="flex flex-wrap items-center justify-end gap-3"><label htmlFor="weight" className="text-sm font-semibold text-slate-500">Peso (kg)</label><FormInput id="weight" type="number" min="20" max="350" step="0.1" label={null} className="w-48" placeholder={metrics.lastWeight ?? 'Peso'} value={weightForm.data.weight} onChange={(event) => weightForm.setData('weight', event.target.value)} error={weightForm.errors.weight} /><SubmitButton className="w-auto" processing={weightForm.processing}>Guardar</SubmitButton></div></form>}
                <div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><section className="flex min-h-72 flex-col items-center justify-center rounded-3xl border border-emerald-100 bg-gradient-to-br from-white to-emerald-50 p-6 text-center shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Última medición de glucosa</p><p className="mt-4 text-6xl font-extrabold">{metrics.latestGlucose ?? '--'} <span className="text-lg font-medium text-slate-500">mg/dL</span></p>{metrics.measurementMoment && <div className="mt-4"><span className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700 shadow-sm"><Clock3 size={14} className="text-cyan-600" />{metrics.measurementMoment}</span></div>}<div className="mt-2"><GlucoseStatusBadge statusKey={metrics.glucoseStatusKey} label={metrics.glucoseStatus} /></div>{!metrics.measurementMoment && !metrics.glucoseStatus && <p className="mt-3 text-sm text-slate-500">Sin registros</p>}</section><ChartCard title="Tendencia semanal" labels={metrics.glucoseLabels} values={metrics.glucoseData} emptyIcon={ChartLine} emptyTitle="Sin suficientes datos de glucosa esta semana" /></div>
                <div className="grid gap-6 md:grid-cols-3"><ProgressMetric title="A1c / Calorías" value={metrics.latestHba1c} unit={metrics.latestHba1c ? '%' : ''} current={`${metrics.caloriesToday} kcal`} goal={`${metrics.calorieGoal} kcal`} percent={metrics.caloriePercent} /><ProgressMetric title="Carbohidratos / Actividad" value={metrics.carbsToday} unit="g" current={`${metrics.activityMinutes} min`} goal={`${metrics.activityGoal} min`} percent={metrics.activityPercent} /><ProgressMetric title="Tiempo en rango / Pasos" value={metrics.timeInRange} unit="%" current={metrics.estimatedSteps} goal={metrics.stepGoal} percent={metrics.stepPercent} /></div>
                <section><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-bold uppercase tracking-wide text-slate-500">Últimas mediciones de glucosa</h2>{recentLogs.length > 0 && <Link href={urls.summary} className="text-sm font-semibold text-cyan-700">Ver historial completo</Link>}</div><Table headers={['Fecha y hora', 'Glucosa', 'Momento', 'HbA1c', 'Estado']}>{recentLogs.length ? recentLogs.map((log) => <tr key={log.id}><td className="px-5 py-4 text-sm">{log.date}</td><td className="px-5 py-4 font-bold">{log.glucose} mg/dL</td><td className="px-5 py-4 text-sm">{log.moment}</td><td className="px-5 py-4 text-sm">{log.hba1c ? `${log.hba1c}%` : '--'}</td><td className="px-5 py-4 text-sm">{log.status}</td></tr>) : <tr><td colSpan="5" className="px-5 py-12 text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-cyan-50 text-cyan-600"><NotepadText size={28} /></span><h3 className="mt-4 font-bold text-slate-900">Tu bitácora está lista</h3><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-500">Aún no tienes registros de glucosa. Comienza tu seguimiento hoy para visualizar tus tendencias y mejorar tu salud.</p><Link href={urls.vitals} className="mt-5 inline-flex items-center gap-2 rounded-full bg-cyan-600 px-5 py-2.5 text-sm font-bold text-white"><Plus size={16} />Registrar glucosa</Link></td></tr>}</Table></section>
                <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-sm font-bold uppercase tracking-wide text-slate-500">Resumen de objetivos saludables</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><p><span className="block text-xs text-slate-500">Rango glucosa</span><strong>{profile.targetMin}–{profile.targetMax} mg/dL</strong></p><p><span className="block text-xs text-slate-500">Meta calorías</span><strong>{metrics.calorieGoal} kcal</strong></p><p><span className="block text-xs text-slate-500">Meta actividad</span><strong>{metrics.activityGoal} min</strong></p></div></section>
            </section>
        </div>
    </AuthenticatedLayout>;
}
