import { Head, Link, useForm } from '@inertiajs/react';

import ChartCard from '../Components/ChartCard';
import FormInput from '../Components/FormInput';
import FormSelect from '../Components/FormSelect';
import SubmitButton from '../Components/SubmitButton';
import Table from '../Components/Table';
import AuthenticatedLayout from '../Layouts/AuthenticatedLayout';

function ProgressMetric({ title, value, unit, current, goal, percent }) {
    return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{title}</p><p className="mt-2 text-3xl font-extrabold">{value ?? '--'}{unit}</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-cyan-500" style={{ width: `${Math.min(percent, 100)}%` }} /></div><p className="mt-2 text-xs text-slate-500">Hoy: {current} · Meta: {goal}</p></section>;
}

export default function Dashboard({ metrics, recentLogs, tip, profile, urls, inviteCode }) {
    const weightForm = useForm({ weight: '' });
    const inviteForm = useForm({ role: 'caregiver' });
    return <AuthenticatedLayout><Head title="Dashboard" />
        <div className="grid gap-6 xl:grid-cols-[19rem_1fr]">
            <aside className="space-y-5">
                <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h1 className="text-xl font-bold">Gestión DiabTrack</h1><nav className="mt-4 grid gap-2"><Link href={urls.summary} className="rounded-2xl bg-slate-100 px-4 py-3 font-semibold">Gráficos y resumen</Link><Link href={urls.vitals} className="rounded-2xl bg-cyan-600 px-4 py-3 font-semibold text-white">Registrar datos</Link><Link href={urls.profile} className="rounded-2xl bg-slate-100 px-4 py-3 font-semibold">Ajustes</Link></nav></section>
                <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xs font-bold uppercase tracking-wide text-slate-500">Tip del día</h2>{tip.isAi && <span className="rounded-full bg-cyan-50 px-2 py-1 text-xs font-semibold text-cyan-700">IA</span>}</div><p className="mt-4 text-sm leading-6 text-slate-600">{tip.text}</p></section>
                <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xs font-bold uppercase tracking-wide text-slate-500">Síntomas hoy</h2><p className="mt-3 text-3xl font-extrabold">{metrics.symptomsToday}</p><p className="text-sm text-slate-500">{metrics.symptomsToday === 1 ? 'síntoma reportado' : 'síntomas reportados'}</p></section>
                <form onSubmit={(event) => { event.preventDefault(); inviteForm.post(urls.invite, { preserveScroll: true }); }} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-bold">Código de vinculación</h2><FormSelect id="invite_role" label="Compartir con" value={inviteForm.data.role} onChange={(event) => inviteForm.setData('role', event.target.value)}><option value="caregiver">Cuidador</option><option value="doctor">Médico</option></FormSelect><SubmitButton processing={inviteForm.processing}>Generar código</SubmitButton>{inviteCode && <p className="mt-4 rounded-xl bg-cyan-50 p-3 text-center font-mono text-xl font-bold tracking-widest text-cyan-800">{inviteCode}</p>}</form>
            </aside>
            <section className="space-y-6">
                {metrics.needsWeightUpdate && <form onSubmit={(event) => { event.preventDefault(); weightForm.post(urls.weight, { preserveScroll: true, onSuccess: () => weightForm.reset() }); }} className="grid gap-4 rounded-3xl border border-amber-200 bg-amber-50 p-5 sm:grid-cols-[1fr_auto] sm:items-end"><FormInput id="weight" type="number" min="20" max="350" step="0.1" label="Actualiza tu peso (kg)" placeholder={metrics.lastWeight ?? 'Peso'} value={weightForm.data.weight} onChange={(event) => weightForm.setData('weight', event.target.value)} error={weightForm.errors.weight} /><SubmitButton processing={weightForm.processing}>Guardar peso</SubmitButton></form>}
                <div className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><section className="rounded-3xl border border-slate-200 bg-white p-8 text-center shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Última medición de glucosa</p><p className="mt-4 text-6xl font-extrabold">{metrics.latestGlucose ?? '--'} <span className="text-lg text-slate-400">mg/dL</span></p><p className="mt-3 text-sm text-slate-500">{metrics.measurementMoment ?? 'Sin registros'}{metrics.glucoseStatus ? ` · ${metrics.glucoseStatus}` : ''}</p></section><ChartCard title="Tendencia semanal" labels={metrics.glucoseLabels} values={metrics.glucoseData} /></div>
                <div className="grid gap-4 md:grid-cols-3"><ProgressMetric title="A1c / Calorías" value={metrics.latestHba1c} unit={metrics.latestHba1c ? '%' : ''} current={`${metrics.caloriesToday} kcal`} goal={`${metrics.calorieGoal} kcal`} percent={metrics.caloriePercent} /><ProgressMetric title="Carbohidratos / Actividad" value={metrics.carbsToday} unit="g" current={`${metrics.activityMinutes} min`} goal={`${metrics.activityGoal} min`} percent={metrics.activityPercent} /><ProgressMetric title="Tiempo en rango / Pasos" value={metrics.timeInRange} unit="%" current={metrics.estimatedSteps} goal={metrics.stepGoal} percent={metrics.stepPercent} /></div>
                <section><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-bold uppercase tracking-wide text-slate-500">Últimas mediciones de glucosa</h2>{recentLogs.length > 0 && <Link href={urls.summary} className="text-sm font-semibold text-cyan-700">Ver historial completo</Link>}</div><Table headers={['Fecha y hora', 'Glucosa', 'Momento', 'HbA1c', 'Estado']}>{recentLogs.length ? recentLogs.map((log) => <tr key={log.id}><td className="px-5 py-4 text-sm">{log.date}</td><td className="px-5 py-4 font-bold">{log.glucose} mg/dL</td><td className="px-5 py-4 text-sm">{log.moment}</td><td className="px-5 py-4 text-sm">{log.hba1c ? `${log.hba1c}%` : '--'}</td><td className="px-5 py-4 text-sm">{log.status}</td></tr>) : <tr><td colSpan="5" className="px-5 py-10 text-center"><p className="font-semibold">Tu bitácora está lista</p><Link href={urls.vitals} className="mt-2 inline-block text-cyan-700">Registrar glucosa</Link></td></tr>}</Table></section>
                <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-sm font-bold uppercase tracking-wide text-slate-500">Resumen de objetivos saludables</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><p><span className="block text-xs text-slate-500">Rango glucosa</span><strong>{profile.targetMin}–{profile.targetMax} mg/dL</strong></p><p><span className="block text-xs text-slate-500">Meta calorías</span><strong>{metrics.calorieGoal} kcal</strong></p><p><span className="block text-xs text-slate-500">Meta actividad</span><strong>{metrics.activityGoal} min</strong></p></div></section>
            </section>
        </div>
    </AuthenticatedLayout>;
}
